import {
  LeaderboardCategory,
  LeaderboardEntity,
  TimeframeFilter,
  Complaint,
  Department,
  IssueCategory,
  JurisdictionTier,
} from '../types';

export const INITIAL_LEADERBOARD_ENTITIES: LeaderboardEntity[] = [
  // ==================== 1. DISTRICTS ====================
  {
    id: 'dist-chennai',
    name: 'Chennai District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Chennai',
    trustScore: 94,
    totalReceived: 4250,
    totalResolved: 4010,
    resolutionRate: 94.3,
    avgResolutionHours: 5.2,
    citizenVerificationRate: 96.8,
    citizenSatisfaction: 4.8,
    escalatedCount: 14,
    reopenedCount: 8,
    slaCompliance: 96.2,
    badges: ['Gold', 'Most Trusted Department', 'Highest Verification Rate'],
    trend: +3.2,
    coordinates: { lat: 13.0827, lng: 80.2707 },
    historicalTrust: [
      { month: 'Apr', score: 89 },
      { month: 'May', score: 91 },
      { month: 'Jun', score: 92 },
      { month: 'Jul', score: 93 },
      { month: 'Aug', score: 93 },
      { month: 'Sep', score: 94 },
    ],
  },
  {
    id: 'dist-coimbatore',
    name: 'Coimbatore District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    trustScore: 92,
    totalReceived: 3120,
    totalResolved: 2940,
    resolutionRate: 94.2,
    avgResolutionHours: 6.8,
    citizenVerificationRate: 95.1,
    citizenSatisfaction: 4.7,
    escalatedCount: 18,
    reopenedCount: 11,
    slaCompliance: 94.8,
    badges: ['Gold', 'Best Citizen Satisfaction'],
    trend: +2.4,
    coordinates: { lat: 11.0168, lng: 76.9558 },
    historicalTrust: [
      { month: 'Apr', score: 87 },
      { month: 'May', score: 88 },
      { month: 'Jun', score: 90 },
      { month: 'Jul', score: 91 },
      { month: 'Aug', score: 91 },
      { month: 'Sep', score: 92 },
    ],
  },
  {
    id: 'dist-madurai',
    name: 'Madurai District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Madurai',
    trustScore: 89,
    totalReceived: 2450,
    totalResolved: 2260,
    resolutionRate: 92.2,
    avgResolutionHours: 8.5,
    citizenVerificationRate: 93.4,
    citizenSatisfaction: 4.5,
    escalatedCount: 26,
    reopenedCount: 15,
    slaCompliance: 92.5,
    badges: ['Silver'],
    trend: +1.8,
    coordinates: { lat: 9.9252, lng: 78.1198 },
    historicalTrust: [
      { month: 'Apr', score: 84 },
      { month: 'May', score: 85 },
      { month: 'Jun', score: 86 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
      { month: 'Sep', score: 89 },
    ],
  },
  {
    id: 'dist-trichy',
    name: 'Tiruchirappalli District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    trustScore: 87,
    totalReceived: 2180,
    totalResolved: 1980,
    resolutionRate: 90.8,
    avgResolutionHours: 9.2,
    citizenVerificationRate: 92.0,
    citizenSatisfaction: 4.4,
    escalatedCount: 30,
    reopenedCount: 19,
    slaCompliance: 91.0,
    badges: ['Silver'],
    trend: +2.1,
    coordinates: { lat: 10.7905, lng: 78.7047 },
    historicalTrust: [
      { month: 'Apr', score: 82 },
      { month: 'May', score: 83 },
      { month: 'Jun', score: 85 },
      { month: 'Jul', score: 85 },
      { month: 'Aug', score: 86 },
      { month: 'Sep', score: 87 },
    ],
  },
  {
    id: 'dist-salem',
    name: 'Salem District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Salem',
    trustScore: 86,
    totalReceived: 1890,
    totalResolved: 1710,
    resolutionRate: 90.4,
    avgResolutionHours: 9.8,
    citizenVerificationRate: 91.2,
    citizenSatisfaction: 4.3,
    escalatedCount: 32,
    reopenedCount: 21,
    slaCompliance: 90.2,
    badges: ['Silver'],
    trend: +1.5,
    coordinates: { lat: 11.6643, lng: 78.146 },
    historicalTrust: [
      { month: 'Apr', score: 81 },
      { month: 'May', score: 83 },
      { month: 'Jun', score: 84 },
      { month: 'Jul', score: 84 },
      { month: 'Aug', score: 85 },
      { month: 'Sep', score: 86 },
    ],
  },
  {
    id: 'dist-tirunelveli',
    name: 'Tirunelveli District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Tirunelveli',
    trustScore: 84,
    totalReceived: 1450,
    totalResolved: 1290,
    resolutionRate: 88.9,
    avgResolutionHours: 11.4,
    citizenVerificationRate: 89.6,
    citizenSatisfaction: 4.2,
    escalatedCount: 38,
    reopenedCount: 24,
    slaCompliance: 88.5,
    badges: ['Silver'],
    trend: +0.9,
    coordinates: { lat: 8.7139, lng: 77.7567 },
    historicalTrust: [
      { month: 'Apr', score: 80 },
      { month: 'May', score: 81 },
      { month: 'Jun', score: 82 },
      { month: 'Jul', score: 83 },
      { month: 'Aug', score: 83 },
      { month: 'Sep', score: 84 },
    ],
  },
  {
    id: 'dist-erode',
    name: 'Erode District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Erode',
    trustScore: 83,
    totalReceived: 1320,
    totalResolved: 1170,
    resolutionRate: 88.6,
    avgResolutionHours: 12.0,
    citizenVerificationRate: 88.9,
    citizenSatisfaction: 4.2,
    escalatedCount: 42,
    reopenedCount: 27,
    slaCompliance: 87.8,
    badges: ['Silver'],
    trend: +1.2,
    coordinates: { lat: 11.341, lng: 77.7172 },
    historicalTrust: [
      { month: 'Apr', score: 79 },
      { month: 'May', score: 80 },
      { month: 'Jun', score: 81 },
      { month: 'Jul', score: 82 },
      { month: 'Aug', score: 82 },
      { month: 'Sep', score: 83 },
    ],
  },
  {
    id: 'dist-vellore',
    name: 'Vellore District',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Tamil Nadu',
    district: 'Vellore',
    trustScore: 78,
    totalReceived: 1180,
    totalResolved: 1010,
    resolutionRate: 85.5,
    avgResolutionHours: 14.5,
    citizenVerificationRate: 86.4,
    citizenSatisfaction: 4.0,
    escalatedCount: 52,
    reopenedCount: 35,
    slaCompliance: 84.6,
    badges: ['Bronze'],
    trend: +0.4,
    coordinates: { lat: 12.9165, lng: 79.1325 },
    historicalTrust: [
      { month: 'Apr', score: 75 },
      { month: 'May', score: 76 },
      { month: 'Jun', score: 77 },
      { month: 'Jul', score: 77 },
      { month: 'Aug', score: 78 },
      { month: 'Sep', score: 78 },
    ],
  },
  {
    id: 'dist-bengaluru',
    name: 'Bengaluru Urban',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    trustScore: 93,
    totalReceived: 5640,
    totalResolved: 5320,
    resolutionRate: 94.3,
    avgResolutionHours: 5.6,
    citizenVerificationRate: 96.1,
    citizenSatisfaction: 4.7,
    escalatedCount: 22,
    reopenedCount: 14,
    slaCompliance: 95.4,
    badges: ['Gold', 'Highest Verification Rate'],
    trend: +3.0,
    coordinates: { lat: 12.9716, lng: 77.5946 },
    historicalTrust: [
      { month: 'Apr', score: 88 },
      { month: 'May', score: 89 },
      { month: 'Jun', score: 91 },
      { month: 'Jul', score: 92 },
      { month: 'Aug', score: 92 },
      { month: 'Sep', score: 93 },
    ],
  },
  {
    id: 'dist-mumbai',
    name: 'Mumbai City',
    category: 'districts',
    tier: 'District Collectorate',
    state: 'Maharashtra',
    district: 'Mumbai City',
    trustScore: 91,
    totalReceived: 6200,
    totalResolved: 5790,
    resolutionRate: 93.3,
    avgResolutionHours: 6.2,
    citizenVerificationRate: 94.8,
    citizenSatisfaction: 4.6,
    escalatedCount: 28,
    reopenedCount: 18,
    slaCompliance: 94.0,
    badges: ['Gold'],
    trend: +2.5,
    coordinates: { lat: 18.9388, lng: 72.8354 },
    historicalTrust: [
      { month: 'Apr', score: 86 },
      { month: 'May', score: 87 },
      { month: 'Jun', score: 89 },
      { month: 'Jul', score: 90 },
      { month: 'Aug', score: 90 },
      { month: 'Sep', score: 91 },
    ],
  },

  // ==================== 2. MUNICIPAL CORPORATIONS ====================
  {
    id: 'corp-chennai',
    name: 'Greater Chennai Corporation (GCC)',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    localBodyType: 'Municipal Corporation',
    trustScore: 95,
    totalReceived: 3890,
    totalResolved: 3710,
    resolutionRate: 95.3,
    avgResolutionHours: 4.8,
    citizenVerificationRate: 97.4,
    citizenSatisfaction: 4.9,
    escalatedCount: 10,
    reopenedCount: 5,
    slaCompliance: 97.1,
    badges: ['Gold', 'Fastest Responder', 'Most Trusted Department', 'Best Citizen Satisfaction'],
    trend: +3.8,
    historicalTrust: [
      { month: 'Apr', score: 90 },
      { month: 'May', score: 92 },
      { month: 'Jun', score: 93 },
      { month: 'Jul', score: 94 },
      { month: 'Aug', score: 94 },
      { month: 'Sep', score: 95 },
    ],
  },
  {
    id: 'corp-coimbatore',
    name: 'Coimbatore City Municipal Corporation',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    localBodyType: 'Municipal Corporation',
    trustScore: 92,
    totalReceived: 2750,
    totalResolved: 2590,
    resolutionRate: 94.1,
    avgResolutionHours: 6.4,
    citizenVerificationRate: 95.3,
    citizenSatisfaction: 4.7,
    escalatedCount: 16,
    reopenedCount: 9,
    slaCompliance: 95.0,
    badges: ['Gold', 'Best Citizen Satisfaction'],
    trend: +2.6,
    historicalTrust: [
      { month: 'Apr', score: 87 },
      { month: 'May', score: 88 },
      { month: 'Jun', score: 90 },
      { month: 'Jul', score: 91 },
      { month: 'Aug', score: 91 },
      { month: 'Sep', score: 92 },
    ],
  },
  {
    id: 'corp-madurai',
    name: 'Madurai City Corporation',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Madurai',
    localBodyType: 'Municipal Corporation',
    trustScore: 89,
    totalReceived: 2100,
    totalResolved: 1940,
    resolutionRate: 92.3,
    avgResolutionHours: 7.9,
    citizenVerificationRate: 93.6,
    citizenSatisfaction: 4.5,
    escalatedCount: 22,
    reopenedCount: 14,
    slaCompliance: 92.8,
    badges: ['Silver'],
    trend: +1.9,
    historicalTrust: [
      { month: 'Apr', score: 84 },
      { month: 'May', score: 85 },
      { month: 'Jun', score: 86 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
      { month: 'Sep', score: 89 },
    ],
  },
  {
    id: 'corp-trichy',
    name: 'Tiruchirappalli City Corporation',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    localBodyType: 'Municipal Corporation',
    trustScore: 88,
    totalReceived: 1840,
    totalResolved: 1680,
    resolutionRate: 91.3,
    avgResolutionHours: 8.6,
    citizenVerificationRate: 92.5,
    citizenSatisfaction: 4.4,
    escalatedCount: 25,
    reopenedCount: 16,
    slaCompliance: 91.6,
    badges: ['Silver'],
    trend: +1.5,
    historicalTrust: [
      { month: 'Apr', score: 83 },
      { month: 'May', score: 84 },
      { month: 'Jun', score: 85 },
      { month: 'Jul', score: 86 },
      { month: 'Aug', score: 87 },
      { month: 'Sep', score: 88 },
    ],
  },
  {
    id: 'corp-salem',
    name: 'Salem City Municipal Corporation',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Salem',
    localBodyType: 'Municipal Corporation',
    trustScore: 86,
    totalReceived: 1620,
    totalResolved: 1460,
    resolutionRate: 90.1,
    avgResolutionHours: 9.4,
    citizenVerificationRate: 91.0,
    citizenSatisfaction: 4.3,
    escalatedCount: 29,
    reopenedCount: 18,
    slaCompliance: 90.0,
    badges: ['Silver'],
    trend: +1.4,
    historicalTrust: [
      { month: 'Apr', score: 81 },
      { month: 'May', score: 82 },
      { month: 'Jun', score: 84 },
      { month: 'Jul', score: 84 },
      { month: 'Aug', score: 85 },
      { month: 'Sep', score: 86 },
    ],
  },
  {
    id: 'corp-tiruppur',
    name: 'Tiruppur City Municipal Corporation',
    category: 'municipal_corporations',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Tiruppur',
    localBodyType: 'Municipal Corporation',
    trustScore: 85,
    totalReceived: 1410,
    totalResolved: 1260,
    resolutionRate: 89.3,
    avgResolutionHours: 10.2,
    citizenVerificationRate: 90.4,
    citizenSatisfaction: 4.3,
    escalatedCount: 34,
    reopenedCount: 22,
    slaCompliance: 89.1,
    badges: ['Silver'],
    trend: +1.1,
    historicalTrust: [
      { month: 'Apr', score: 80 },
      { month: 'May', score: 81 },
      { month: 'Jun', score: 82 },
      { month: 'Jul', score: 83 },
      { month: 'Aug', score: 84 },
      { month: 'Sep', score: 85 },
    ],
  },

  // ==================== 3. MUNICIPALITIES ====================
  {
    id: 'muni-tambaram',
    name: 'Tambaram Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Chennai',
    localBodyType: 'Municipality',
    trustScore: 92,
    totalReceived: 980,
    totalResolved: 925,
    resolutionRate: 94.3,
    avgResolutionHours: 5.9,
    citizenVerificationRate: 95.8,
    citizenSatisfaction: 4.7,
    escalatedCount: 7,
    reopenedCount: 4,
    slaCompliance: 95.2,
    badges: ['Gold', 'Fastest Responder', 'Zero Pending Complaints'],
    trend: +3.1,
    historicalTrust: [
      { month: 'Apr', score: 86 },
      { month: 'May', score: 88 },
      { month: 'Jun', score: 89 },
      { month: 'Jul', score: 90 },
      { month: 'Aug', score: 91 },
      { month: 'Sep', score: 92 },
    ],
  },
  {
    id: 'muni-avadi',
    name: 'Avadi Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Thiruvallur',
    localBodyType: 'Municipality',
    trustScore: 89,
    totalReceived: 840,
    totalResolved: 780,
    resolutionRate: 92.8,
    avgResolutionHours: 7.2,
    citizenVerificationRate: 94.1,
    citizenSatisfaction: 4.5,
    escalatedCount: 11,
    reopenedCount: 6,
    slaCompliance: 93.4,
    badges: ['Silver', 'Best Citizen Satisfaction'],
    trend: +2.2,
    historicalTrust: [
      { month: 'Apr', score: 83 },
      { month: 'May', score: 85 },
      { month: 'Jun', score: 86 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
      { month: 'Sep', score: 89 },
    ],
  },
  {
    id: 'muni-kanchipuram',
    name: 'Kanchipuram Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    localBodyType: 'Municipality',
    trustScore: 87,
    totalReceived: 760,
    totalResolved: 695,
    resolutionRate: 91.4,
    avgResolutionHours: 8.4,
    citizenVerificationRate: 92.3,
    citizenSatisfaction: 4.4,
    escalatedCount: 15,
    reopenedCount: 9,
    slaCompliance: 91.8,
    badges: ['Silver'],
    trend: +1.8,
    historicalTrust: [
      { month: 'Apr', score: 82 },
      { month: 'May', score: 83 },
      { month: 'Jun', score: 84 },
      { month: 'Jul', score: 85 },
      { month: 'Aug', score: 86 },
      { month: 'Sep', score: 87 },
    ],
  },
  {
    id: 'muni-cuddalore',
    name: 'Cuddalore Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Cuddalore',
    localBodyType: 'Municipality',
    trustScore: 85,
    totalReceived: 690,
    totalResolved: 620,
    resolutionRate: 89.8,
    avgResolutionHours: 9.6,
    citizenVerificationRate: 90.6,
    citizenSatisfaction: 4.3,
    escalatedCount: 19,
    reopenedCount: 12,
    slaCompliance: 89.7,
    badges: ['Silver'],
    trend: +1.2,
    historicalTrust: [
      { month: 'Apr', score: 80 },
      { month: 'May', score: 81 },
      { month: 'Jun', score: 82 },
      { month: 'Jul', score: 83 },
      { month: 'Aug', score: 84 },
      { month: 'Sep', score: 85 },
    ],
  },
  {
    id: 'muni-dindigul',
    name: 'Dindigul Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Dindigul',
    localBodyType: 'Municipality',
    trustScore: 84,
    totalReceived: 620,
    totalResolved: 550,
    resolutionRate: 88.7,
    avgResolutionHours: 10.4,
    citizenVerificationRate: 89.5,
    citizenSatisfaction: 4.2,
    escalatedCount: 22,
    reopenedCount: 15,
    slaCompliance: 88.4,
    badges: ['Silver'],
    trend: +0.9,
    historicalTrust: [
      { month: 'Apr', score: 79 },
      { month: 'May', score: 80 },
      { month: 'Jun', score: 81 },
      { month: 'Jul', score: 82 },
      { month: 'Aug', score: 83 },
      { month: 'Sep', score: 84 },
    ],
  },
  {
    id: 'muni-karur',
    name: 'Karur Municipality',
    category: 'municipalities',
    tier: 'Municipality',
    state: 'Tamil Nadu',
    district: 'Karur',
    localBodyType: 'Municipality',
    trustScore: 82,
    totalReceived: 540,
    totalResolved: 475,
    resolutionRate: 87.9,
    avgResolutionHours: 11.2,
    citizenVerificationRate: 88.2,
    citizenSatisfaction: 4.1,
    escalatedCount: 26,
    reopenedCount: 18,
    slaCompliance: 87.0,
    badges: ['Silver'],
    trend: +1.0,
    historicalTrust: [
      { month: 'Apr', score: 77 },
      { month: 'May', score: 78 },
      { month: 'Jun', score: 79 },
      { month: 'Jul', score: 80 },
      { month: 'Aug', score: 81 },
      { month: 'Sep', score: 82 },
    ],
  },

  // ==================== 4. TOWN PANCHAYATS ====================
  {
    id: 'tp-alandur',
    name: 'Alandur Town Panchayat',
    category: 'town_panchayats',
    tier: 'Town Panchayat',
    state: 'Tamil Nadu',
    district: 'Chennai',
    localBodyType: 'Town Panchayat',
    trustScore: 93,
    totalReceived: 480,
    totalResolved: 460,
    resolutionRate: 95.8,
    avgResolutionHours: 5.1,
    citizenVerificationRate: 96.5,
    citizenSatisfaction: 4.8,
    escalatedCount: 3,
    reopenedCount: 2,
    slaCompliance: 96.9,
    badges: ['Gold', 'Fastest Responder', 'Zero Pending Complaints'],
    trend: +3.5,
    historicalTrust: [
      { month: 'Apr', score: 87 },
      { month: 'May', score: 89 },
      { month: 'Jun', score: 90 },
      { month: 'Jul', score: 91 },
      { month: 'Aug', score: 92 },
      { month: 'Sep', score: 93 },
    ],
  },
  {
    id: 'tp-sholinganallur',
    name: 'Sholinganallur Town Panchayat',
    category: 'town_panchayats',
    tier: 'Town Panchayat',
    state: 'Tamil Nadu',
    district: 'Chennai',
    localBodyType: 'Town Panchayat',
    trustScore: 91,
    totalReceived: 420,
    totalResolved: 398,
    resolutionRate: 94.7,
    avgResolutionHours: 5.8,
    citizenVerificationRate: 95.2,
    citizenSatisfaction: 4.7,
    escalatedCount: 5,
    reopenedCount: 3,
    slaCompliance: 95.5,
    badges: ['Gold', 'Highest Verification Rate'],
    trend: +2.8,
    historicalTrust: [
      { month: 'Apr', score: 85 },
      { month: 'May', score: 87 },
      { month: 'Jun', score: 88 },
      { month: 'Jul', score: 89 },
      { month: 'Aug', score: 90 },
      { month: 'Sep', score: 91 },
    ],
  },
  {
    id: 'tp-sriperumbudur',
    name: 'Sriperumbudur Town Panchayat',
    category: 'town_panchayats',
    tier: 'Town Panchayat',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    localBodyType: 'Town Panchayat',
    trustScore: 88,
    totalReceived: 360,
    totalResolved: 330,
    resolutionRate: 91.6,
    avgResolutionHours: 7.4,
    citizenVerificationRate: 93.0,
    citizenSatisfaction: 4.5,
    escalatedCount: 8,
    reopenedCount: 5,
    slaCompliance: 92.4,
    badges: ['Silver'],
    trend: +2.0,
    historicalTrust: [
      { month: 'Apr', score: 82 },
      { month: 'May', score: 83 },
      { month: 'Jun', score: 85 },
      { month: 'Jul', score: 86 },
      { month: 'Aug', score: 87 },
      { month: 'Sep', score: 88 },
    ],
  },
  {
    id: 'tp-mamallapuram',
    name: 'Mamallapuram Heritage Town Panchayat',
    category: 'town_panchayats',
    tier: 'Town Panchayat',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    localBodyType: 'Town Panchayat',
    trustScore: 87,
    totalReceived: 310,
    totalResolved: 282,
    resolutionRate: 90.9,
    avgResolutionHours: 8.0,
    citizenVerificationRate: 92.1,
    citizenSatisfaction: 4.4,
    escalatedCount: 9,
    reopenedCount: 6,
    slaCompliance: 91.5,
    badges: ['Silver'],
    trend: +1.6,
    historicalTrust: [
      { month: 'Apr', score: 81 },
      { month: 'May', score: 82 },
      { month: 'Jun', score: 84 },
      { month: 'Jul', score: 85 },
      { month: 'Aug', score: 86 },
      { month: 'Sep', score: 87 },
    ],
  },
  {
    id: 'tp-thirukalukundram',
    name: 'Thirukalukundram Town Panchayat',
    category: 'town_panchayats',
    tier: 'Town Panchayat',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    localBodyType: 'Town Panchayat',
    trustScore: 84,
    totalReceived: 270,
    totalResolved: 240,
    resolutionRate: 88.8,
    avgResolutionHours: 9.6,
    citizenVerificationRate: 89.8,
    citizenSatisfaction: 4.2,
    escalatedCount: 12,
    reopenedCount: 8,
    slaCompliance: 89.2,
    badges: ['Silver'],
    trend: +1.1,
    historicalTrust: [
      { month: 'Apr', score: 78 },
      { month: 'May', score: 79 },
      { month: 'Jun', score: 81 },
      { month: 'Jul', score: 82 },
      { month: 'Aug', score: 83 },
      { month: 'Sep', score: 84 },
    ],
  },

  // ==================== 5. VILLAGE PANCHAYATS ====================
  {
    id: 'vp-mudichur',
    name: 'Mudichur Village Panchayat',
    category: 'village_panchayats',
    tier: 'Village Panchayat',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    localBodyType: 'Village Panchayat',
    trustScore: 94,
    totalReceived: 240,
    totalResolved: 232,
    resolutionRate: 96.6,
    avgResolutionHours: 4.6,
    citizenVerificationRate: 97.5,
    citizenSatisfaction: 4.9,
    escalatedCount: 2,
    reopenedCount: 1,
    slaCompliance: 97.4,
    badges: ['Gold', 'Fastest Responder', 'Zero Pending Complaints', 'Best Citizen Satisfaction'],
    trend: +4.2,
    historicalTrust: [
      { month: 'Apr', score: 88 },
      { month: 'May', score: 90 },
      { month: 'Jun', score: 91 },
      { month: 'Jul', score: 92 },
      { month: 'Aug', score: 93 },
      { month: 'Sep', score: 94 },
    ],
  },
  {
    id: 'vp-medavakkam',
    name: 'Medavakkam Village Panchayat',
    category: 'village_panchayats',
    tier: 'Village Panchayat',
    state: 'Tamil Nadu',
    district: 'Chennai',
    localBodyType: 'Village Panchayat',
    trustScore: 91,
    totalReceived: 210,
    totalResolved: 200,
    resolutionRate: 95.2,
    avgResolutionHours: 5.4,
    citizenVerificationRate: 95.8,
    citizenSatisfaction: 4.7,
    escalatedCount: 4,
    reopenedCount: 2,
    slaCompliance: 96.0,
    badges: ['Gold', 'Highest Verification Rate'],
    trend: +2.9,
    historicalTrust: [
      { month: 'Apr', score: 85 },
      { month: 'May', score: 87 },
      { month: 'Jun', score: 88 },
      { month: 'Jul', score: 89 },
      { month: 'Aug', score: 90 },
      { month: 'Sep', score: 91 },
    ],
  },
  {
    id: 'vp-kovilambakkam',
    name: 'Kovilambakkam Village Panchayat',
    category: 'village_panchayats',
    tier: 'Village Panchayat',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    localBodyType: 'Village Panchayat',
    trustScore: 89,
    totalReceived: 185,
    totalResolved: 172,
    resolutionRate: 92.9,
    avgResolutionHours: 6.8,
    citizenVerificationRate: 93.9,
    citizenSatisfaction: 4.6,
    escalatedCount: 5,
    reopenedCount: 3,
    slaCompliance: 93.8,
    badges: ['Silver'],
    trend: +2.1,
    historicalTrust: [
      { month: 'Apr', score: 83 },
      { month: 'May', score: 84 },
      { month: 'Jun', score: 86 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
      { month: 'Sep', score: 89 },
    ],
  },
  {
    id: 'vp-vandalur',
    name: 'Vandalur Model Village Panchayat',
    category: 'village_panchayats',
    tier: 'Village Panchayat',
    state: 'Tamil Nadu',
    district: 'Chengalpattu',
    localBodyType: 'Village Panchayat',
    trustScore: 86,
    totalReceived: 160,
    totalResolved: 146,
    resolutionRate: 91.2,
    avgResolutionHours: 8.2,
    citizenVerificationRate: 92.0,
    citizenSatisfaction: 4.4,
    escalatedCount: 7,
    reopenedCount: 4,
    slaCompliance: 91.5,
    badges: ['Silver'],
    trend: +1.5,
    historicalTrust: [
      { month: 'Apr', score: 80 },
      { month: 'May', score: 82 },
      { month: 'Jun', score: 83 },
      { month: 'Jul', score: 84 },
      { month: 'Aug', score: 85 },
      { month: 'Sep', score: 86 },
    ],
  },
  {
    id: 'vp-padappai',
    name: 'Padappai Village Panchayat',
    category: 'village_panchayats',
    tier: 'Village Panchayat',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    localBodyType: 'Village Panchayat',
    trustScore: 83,
    totalReceived: 140,
    totalResolved: 124,
    resolutionRate: 88.5,
    avgResolutionHours: 9.8,
    citizenVerificationRate: 89.2,
    citizenSatisfaction: 4.2,
    escalatedCount: 9,
    reopenedCount: 6,
    slaCompliance: 89.0,
    badges: ['Silver'],
    trend: +1.0,
    historicalTrust: [
      { month: 'Apr', score: 78 },
      { month: 'May', score: 79 },
      { month: 'Jun', score: 80 },
      { month: 'Jul', score: 81 },
      { month: 'Aug', score: 82 },
      { month: 'Sep', score: 83 },
    ],
  },

  // ==================== 6. DEPARTMENTS ====================
  {
    id: 'dept-sanitation',
    name: 'Sanitation & Solid Waste',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Garbage',
    trustScore: 96,
    totalReceived: 2150,
    totalResolved: 2060,
    resolutionRate: 95.8,
    avgResolutionHours: 3.8,
    citizenVerificationRate: 97.6,
    citizenSatisfaction: 4.9,
    escalatedCount: 6,
    reopenedCount: 3,
    slaCompliance: 98.1,
    badges: ['Gold', 'Fastest Responder', 'Most Trusted Department', 'Best Citizen Satisfaction'],
    trend: +4.1,
    historicalTrust: [
      { month: 'Apr', score: 91 },
      { month: 'May', score: 92 },
      { month: 'Jun', score: 94 },
      { month: 'Jul', score: 95 },
      { month: 'Aug', score: 95 },
      { month: 'Sep', score: 96 },
    ],
  },
  {
    id: 'dept-roads',
    name: 'Roads & Highways Department',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Road Damage',
    trustScore: 93,
    totalReceived: 1980,
    totalResolved: 1860,
    resolutionRate: 93.9,
    avgResolutionHours: 5.4,
    citizenVerificationRate: 96.0,
    citizenSatisfaction: 4.7,
    escalatedCount: 14,
    reopenedCount: 7,
    slaCompliance: 95.8,
    badges: ['Gold', 'Highest Verification Rate'],
    trend: +3.2,
    historicalTrust: [
      { month: 'Apr', score: 88 },
      { month: 'May', score: 89 },
      { month: 'Jun', score: 91 },
      { month: 'Jul', score: 92 },
      { month: 'Aug', score: 92 },
      { month: 'Sep', score: 93 },
    ],
  },
  {
    id: 'dept-water',
    name: 'Water Supply (Metro Water)',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Water Leakage',
    trustScore: 91,
    totalReceived: 1650,
    totalResolved: 1530,
    resolutionRate: 92.7,
    avgResolutionHours: 6.2,
    citizenVerificationRate: 94.8,
    citizenSatisfaction: 4.6,
    escalatedCount: 18,
    reopenedCount: 9,
    slaCompliance: 94.2,
    badges: ['Gold'],
    trend: +2.5,
    historicalTrust: [
      { month: 'Apr', score: 85 },
      { month: 'May', score: 87 },
      { month: 'Jun', score: 88 },
      { month: 'Jul', score: 90 },
      { month: 'Aug', score: 90 },
      { month: 'Sep', score: 91 },
    ],
  },
  {
    id: 'dept-electricity',
    name: 'Electricity Board (TANGEDCO)',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Power Failure',
    trustScore: 90,
    totalReceived: 1820,
    totalResolved: 1690,
    resolutionRate: 92.8,
    avgResolutionHours: 4.2,
    citizenVerificationRate: 94.2,
    citizenSatisfaction: 4.6,
    escalatedCount: 19,
    reopenedCount: 10,
    slaCompliance: 95.0,
    badges: ['Gold', 'Fastest Responder'],
    trend: +2.8,
    historicalTrust: [
      { month: 'Apr', score: 84 },
      { month: 'May', score: 86 },
      { month: 'Jun', score: 87 },
      { month: 'Jul', score: 89 },
      { month: 'Aug', score: 89 },
      { month: 'Sep', score: 90 },
    ],
  },
  {
    id: 'dept-pwd',
    name: 'Public Works Department (PWD)',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Drainage',
    trustScore: 88,
    totalReceived: 1420,
    totalResolved: 1290,
    resolutionRate: 90.8,
    avgResolutionHours: 8.5,
    citizenVerificationRate: 92.6,
    citizenSatisfaction: 4.4,
    escalatedCount: 24,
    reopenedCount: 13,
    slaCompliance: 91.5,
    badges: ['Silver'],
    trend: +1.9,
    historicalTrust: [
      { month: 'Apr', score: 82 },
      { month: 'May', score: 84 },
      { month: 'Jun', score: 85 },
      { month: 'Jul', score: 86 },
      { month: 'Aug', score: 87 },
      { month: 'Sep', score: 88 },
    ],
  },
  {
    id: 'dept-parks',
    name: 'Parks & Horticulture Department',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Fallen Tree',
    trustScore: 89,
    totalReceived: 920,
    totalResolved: 860,
    resolutionRate: 93.4,
    avgResolutionHours: 5.6,
    citizenVerificationRate: 93.8,
    citizenSatisfaction: 4.5,
    escalatedCount: 11,
    reopenedCount: 6,
    slaCompliance: 93.9,
    badges: ['Silver', 'Zero Pending Complaints'],
    trend: +2.2,
    historicalTrust: [
      { month: 'Apr', score: 83 },
      { month: 'May', score: 84 },
      { month: 'Jun', score: 86 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
      { month: 'Sep', score: 89 },
    ],
  },
  {
    id: 'dept-traffic',
    name: 'Traffic Police & Signals',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Traffic Signal',
    trustScore: 87,
    totalReceived: 1150,
    totalResolved: 1040,
    resolutionRate: 90.4,
    avgResolutionHours: 6.9,
    citizenVerificationRate: 91.9,
    citizenSatisfaction: 4.4,
    escalatedCount: 22,
    reopenedCount: 12,
    slaCompliance: 91.8,
    badges: ['Silver'],
    trend: +1.7,
    historicalTrust: [
      { month: 'Apr', score: 81 },
      { month: 'May', score: 83 },
      { month: 'Jun', score: 84 },
      { month: 'Jul', score: 85 },
      { month: 'Aug', score: 86 },
      { month: 'Sep', score: 87 },
    ],
  },
  {
    id: 'dept-drainage',
    name: 'Drainage & Sewerage Board',
    category: 'departments',
    tier: 'Municipal Corporation',
    state: 'Tamil Nadu',
    district: 'Chennai',
    departmentCategory: 'Drainage',
    trustScore: 85,
    totalReceived: 1580,
    totalResolved: 1390,
    resolutionRate: 87.9,
    avgResolutionHours: 9.8,
    citizenVerificationRate: 90.1,
    citizenSatisfaction: 4.3,
    escalatedCount: 31,
    reopenedCount: 19,
    slaCompliance: 88.6,
    badges: ['Silver'],
    trend: +1.2,
    historicalTrust: [
      { month: 'Apr', score: 79 },
      { month: 'May', score: 80 },
      { month: 'Jun', score: 82 },
      { month: 'Jul', score: 83 },
      { month: 'Aug', score: 84 },
      { month: 'Sep', score: 85 },
    ],
  },
];

export const leaderboardService = {
  /**
   * Recompute dynamic leaderboard scores by factoring in live complaints and departments
   */
  getDynamicLeaderboard(
    liveComplaints: Complaint[],
    liveDepartments: Department[]
  ): LeaderboardEntity[] {
    return INITIAL_LEADERBOARD_ENTITIES.map((base) => {
      // Find matching live department if applicable
      const matchingDept = liveDepartments.find(
        (d) =>
          d.id === base.id ||
          d.name.toLowerCase() === base.name.toLowerCase() ||
          (base.departmentCategory && d.category === base.departmentCategory)
      );

      // Filter live complaints that belong to this entity
      const entityComplaints = liveComplaints.filter((c) => {
        if (base.category === 'departments') {
          return c.department.toLowerCase().includes(base.name.toLowerCase()) || c.category === base.departmentCategory;
        }
        if (base.category === 'districts') {
          return c.location.district.toLowerCase() === base.district.toLowerCase();
        }
        return c.location.jurisdictionTier === base.tier || c.location.district.toLowerCase() === base.district.toLowerCase();
      });

      // Calculate live adjustments
      const liveResolvedCount = entityComplaints.filter((c) =>
        ['Resolved', 'Closed'].includes(c.status)
      ).length;
      const liveEscalatedCount = entityComplaints.filter((c) => c.isEscalated || c.status === 'Escalated').length;
      const liveReopenedCount = entityComplaints.filter(
        (c) => c.verification && c.verification.isSatisfied === false
      ).length;
      const liveVerifiedCount = entityComplaints.filter(
        (c) => c.verification && c.verification.isSatisfied === true
      ).length;

      const totalReceived = base.totalReceived + entityComplaints.length;
      const totalResolved = base.totalResolved + liveResolvedCount;
      const resolutionRate = Number(((totalResolved / Math.max(1, totalReceived)) * 100).toFixed(1));

      // Calculate dynamic trust score
      let trustScore = base.trustScore;
      if (matchingDept) {
        trustScore = matchingDept.trustScore;
      }
      // Apply delta from live verification and escalations
      if (liveVerifiedCount > 0) trustScore = Math.min(100, trustScore + liveVerifiedCount * 1.5);
      if (liveEscalatedCount > 0) trustScore = Math.max(40, trustScore - liveEscalatedCount * 2);
      if (liveReopenedCount > 0) trustScore = Math.max(40, trustScore - liveReopenedCount * 3);
      trustScore = Math.round(trustScore);

      const citizenVerificationRate = Number(
        Math.min(99.5, base.citizenVerificationRate + (liveVerifiedCount > 0 ? 0.8 : 0)).toFixed(1)
      );

      const escalatedCount = base.escalatedCount + liveEscalatedCount;
      const reopenedCount = base.reopenedCount + liveReopenedCount;

      // Assign Badges
      const badges: string[] = [];
      if (trustScore >= 90) badges.push('Gold');
      else if (trustScore >= 80) badges.push('Silver');
      else if (trustScore >= 70) badges.push('Bronze');

      if (base.avgResolutionHours <= 6) badges.push('Fastest Responder');
      if (trustScore >= 94) badges.push('Most Trusted Department');
      if (base.citizenSatisfaction >= 4.7) badges.push('Best Citizen Satisfaction');
      if (citizenVerificationRate >= 95.0) badges.push('Highest Verification Rate');
      if (totalReceived - totalResolved <= 15) badges.push('Zero Pending Complaints');

      // Update latest month score in history
      const updatedHistory = [...base.historicalTrust];
      if (updatedHistory.length > 0) {
        updatedHistory[updatedHistory.length - 1] = {
          month: updatedHistory[updatedHistory.length - 1].month,
          score: trustScore,
        };
      }

      return {
        ...base,
        totalReceived,
        totalResolved,
        resolutionRate,
        trustScore,
        citizenVerificationRate,
        escalatedCount,
        reopenedCount,
        badges,
        historicalTrust: updatedHistory,
      };
    });
  },

  /**
   * Filter and rank entities
   */
  filterAndRank(
    entities: LeaderboardEntity[],
    filters: {
      category: LeaderboardCategory;
      state: string;
      district: string;
      localBody: string;
      department: string;
      timeframe: TimeframeFilter;
    }
  ): (LeaderboardEntity & { rank: number })[] {
    const filtered = entities.filter((item) => {
      // 1. Category
      if (item.category !== filters.category) return false;

      // 2. State
      if (filters.state !== 'All' && item.state !== filters.state) return false;

      // 3. District
      if (filters.district !== 'All' && item.district !== filters.district) return false;

      // 4. Local Body
      if (filters.localBody !== 'All') {
        if (item.localBodyType && item.localBodyType !== filters.localBody) return false;
      }

      // 5. Department
      if (filters.department !== 'All') {
        if (item.departmentCategory && item.departmentCategory !== filters.department) return false;
      }

      return true;
    });

    // Timeframe factor adjustment (weekly/monthly/quarterly/yearly simulation)
    const adjusted = filtered.map((e) => {
      let volumeMultiplier = 1;
      if (filters.timeframe === 'Weekly') {
        volumeMultiplier = 0.25;
      } else if (filters.timeframe === 'Quarterly') {
        volumeMultiplier = 2.8;
      } else if (filters.timeframe === 'Yearly') {
        volumeMultiplier = 11.2;
      }

      return {
        ...e,
        totalReceived: Math.round(e.totalReceived * volumeMultiplier),
        totalResolved: Math.round(e.totalResolved * volumeMultiplier),
      };
    });

    // Sort by Trust Score descending, then by Resolution Rate descending
    adjusted.sort((a, b) => {
      if (b.trustScore !== a.trustScore) return b.trustScore - a.trustScore;
      return b.resolutionRate - a.resolutionRate;
    });

    return adjusted.map((item, idx) => ({
      ...item,
      rank: idx + 1,
    }));
  },
};
